export const education = [
  { id: 'apprenticeship', type: 'education', sort_order: 1,
    title: 'ICT Associate Professional — Level 6 Apprenticeship',
    subtitle: 'DDLETB Tallaght · FIT Apprenticeship Programme',
    period: 'Oct 2024 — Oct 2026', verify_url: null },
  { id: 'leaving-cert', type: 'education', sort_order: 2,
    title: 'Leaving Certificate',
    subtitle: 'Le Chéile Secondary School, Dublin',
    period: 'Sep 2017 — May 2022', verify_url: null },

  { id: 'az900', type: 'certification', sort_order: 1,
    title: 'Microsoft Certified: Azure Fundamentals (AZ-900)',
    subtitle: 'Microsoft', period: 'Jan 2026', verify_url: null },
  { id: 'ai-fund', type: 'certification', sort_order: 2,
    title: 'AI Fundamentals',
    subtitle: 'IBM SkillsBuild', period: 'Oct 2024', verify_url: null },
  { id: 'webdev', type: 'certification', sort_order: 3,
    title: 'Web Development Fundamentals',
    subtitle: 'IBM SkillsBuild', period: 'Aug 2024', verify_url: null },
  { id: 'gle-ai', type: 'certification', sort_order: 4,
    title: 'Guided Learning Experience in AI',
    subtitle: 'SkillUpOnline / IBM SkillsBuild', period: 'Jun — Dec 2024', verify_url: null },
  { id: 'python-100', type: 'certification', sort_order: 5,
    title: '100 Days of Code: Complete Python Pro Bootcamp',
    subtitle: 'Udemy · 58.5 hrs', period: 'Apr 2024', verify_url: null },
]
